FORMAT: 1A
HOST: https://fmx.forevermark.com/api/v1/

# Forevermark FMX Diamond Search

Forevermark's FMX Diamond Search is an API used for fetching diamond search results.


## Authenticated Requests

For every authenticated API call, callers must include the following HTTP request header values:
* `AUTHORIZATION`

Authenticated API call endpoints begin with the route, `/api/v1/`.

Value for `AUTHORIZATION` should be set to "Bearer {token}".

When making authenticated API calls, the caller should handle the following possible error responses:

```
{
    "error" : {
        "status": 401,
        "message": "Unauthorized",
        "reason": "TOKEN_INVALID"
    }
}
```

```
{
    "error" : {
        "status": 401,
        "message": "Unauthorized",
        "reason": "TOKEN_EXPIRED"
    }
}
```

Error response meanings:
* `TOKEN_INVALID`: Either the "AUTHORIZATION" header is malformed, or the caller sent an unknown token value.
* `TOKEN_EXPIRED`: The caller sent a token that was valid, but has since expired. The caller should request a new authentication token by calling `CREATE-SESSION`.


## Sessions Collection [/sessions]

### CREATE-SESSION [POST]

Callers use this endpoint to receive an authentication token (session ID).  Callers provide username and password credentials, and if correct, the server responds back with an authentication token (session ID).

+ Request (application/json)

        {
            "username": "john.doe@fmx.forevermark.com",
            "password": "password"
        }

+ Response 201 (application/json)

        {
            "session_id": "a3296040ed7a28289c4dda14c6238e31",
            "user_id": 1,
            "token": "a3296040ed7a28289c4dda14c6238e31",
            "issued_at": "2018-02-02T23:39:50.802Z",
            "expires_at": "2018-02-09T23:39:50.802Z"
        }

+ Response 401 (application/json)

        {
            "error" : {
                "status": 401,
                "message": "Unauthorized",
                "reason": "INVALID_USERNAME_OR_PASSWORD"
            }
        }


## Session [/sessions/{session_id}]

### DELETE-SESSION [DELETE]

Callers use this endpoint to "logout". This can be useful for tracking usage metrics, as well as expiring session authentication tokens.

+ Response 204 (application/json)


## User [/users/{user_id}]

+ Parameters
    + user_id: `1` (number, required) - Userid.

### GET-USER [GET]

+ Response 200 (application/json)

        {
            "user_id": 1,
            "first_name": "John",
            "last_name": "Doe",
            "permissions": {
                "shapes": {
                    "fire_cushion": 1,
                    "fire_mark": 1
                }
            }
        }

+ Response 401 (application/json)

        {
            "error" : {
                "status": 401,
                "message": "Unauthorized",
                "reason": "TOKEN_INVALID"
            }
        }

+ Response 403 (application/json)

        {
            "error" : {
                "status": 403,
                "message": "Unauthorized",
                "reason": "ACCESS_DENIED"
            }
        }


## Diamond [/diamonds/detail/{diamond_id}]

+ Parameters
    + diamond_id: `98733222` (number, required) - ID of requested diamond.

### GET-DIAMOND [GET]

+ Response 200 (application/json)

        {
            "diamond_id": "98733222",
            "shape": "SQ",
            "carat": 3.33,
            "color": "F",
            "clarity": "IF",
            "cut": "EX",
            "lab": "FDI",
            "measurements": "5.30 x 6.30 x 3.10",
            "lw_ratio": "0.88:1",
            "polish": "EX",
            "symmetry": "VG",
            "fluor": "NON",
            "fmd": "Crossworks",
            "report_id": "987654321",
            "report_url": "https://fmx.forevermark.com/certificate.htm?b=manual&f=1/9594.pdf",
            "report_date": "Jan-01",
            "price_per_carat": 20,
            "price": 1500.00,
            "graded": "Y",
            "matched_pair_id": "22233789",
            "table": 0.539,
            "depth": 0.623,
            "barcode": "20000418248",
            "crown_angle": 34.8,
            "crown_height": 15.2,
            "star_length": 1.0,
            "girdle_percent": 4.1,
            "girdle_lower": 1.1,
            "pavilion_angle": 40.8,
            "pavilion_depth": 10.1,
            "culet": "NON",
            "features": "Indented Natural,Knot,Twinning Wisp",
            "comments": "44850167",
            "company": {
                "name": "Crossworks",
                "address_1": "2101 Fourth Avenue",
                "address_2": "Suite 1320",
                "city": "Seattle",
                "country": "US",
                "phone": "(604) 669-9562",
                "fax": "(604) 669-9562",
                "email": "email@crossworks.com",
                "website": "https://crossworks.com"
            }
        }


## Diamond Search Collection [/diamonds/search]

### CREATE-DIAMOND-SEARCH [POST]

+ Request (application/json)

        {
            "rpp": 50,
            "page": 1,
            "sort_by": "diamonds.carat",
            "sort_dir": "DESC",
            "shape": ["RBC", "SQ", "AS"],
            "color_type": "white",
            "color_min": "D",
            "color_max": "L",
            "price_min": 0,
            "price_max": 10000000,
            "diamonds": ["uploaded", "fresh", "inscription", "graded"],
            "cuts": ["BL", "EX", "VG"],
            "clarity_min": "SI2",
            "clarity_max": "FL",
            "carat_min": 0.14,
            "carat_max": 30.00,
            "ppc_min": 0,
            "ppc_max": 300000,
            "table_min": 0.00,
            "table_max": 100.00,
            "depth_min": 0.00,
            "depth_max": 100.00,
            "length_width_min": 0.00,
            "length_width_max": 2.00,
            "matches": "single"
        }

+ Response 200 (application/json)

        {
            "total_results": 2,
            "page": 1,
            "limit": 20,
            "results": [
                {
                    "diamond_id": "98733222",
                    "shape": "SQ",
                    "carat": 3.33,
                    "color": "F",
                    "clarity": "IF",
                    "cut": "EX",
                    "lab": "FDI",
                    "measurements": "5.30 x 6.30 x 3.10",
                    "lw_ratio": "0.88:1",
                    "polish": "EX",
                    "symmetry": "VG",
                    "fluor": "NON",
                    "fmd": "Crossworks"
                    "report_id": "987654321",
                    "report_url": "https://fmx.forevermark.com/certificate.htm?b=manual&f=1/9594.pdf",
                    "price_per_carat": 20,
                    "price": 1500.00,
                    "graded": "Y"
                },
                {
                    "diamond_id": "65534422",
                    "shape": "RND",
                    "carat": 4.05,
                    "color": "H",
                    "clarity": "VVS1",
                    "cut": "BL",
                    "lab": "FDI",
                    "measurements": "7.60 x 7.59 x 5.55",
                    "lw_ratio": "1.00:1",
                    "polish": "VG",
                    "symmetry": "EX",
                    "fluor": "N",
                    "fmd": "BlueChannel, Inc."
                    "report_id": "123456789",
                    "report_url": "https://fmx.forevermark.com/certificate.htm?b=manual&f=1/4543.pdf",
                    "price_per_carat": 30,
                    "price": 1000.00,
                    "graded": "Y"
                }
            ]
        }